sonar.projectKey=ICWAVI:carapp-versioninfo
sonar.host.url=https://devstack.vwgroup.com/sonar
sonar.sources=projects/foreground/src
sonar.tests=projects/foreground
sonar.test.inclusions=projects/**/*.spec.ts
#sonar.cobertura.reportPath=tests/coverage/cobertura-coverage.xml
#sonar.exclusions=projects/background/**/*
sonar.testExecutionReportPaths=junit_sonar_report.xml
sonar.core.codeCoveragePlugin=clover
sonar.clover.reportPath=coverage/clover.xml
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEnconding=UTF-8
sonar.qualitygate.wait=true